import type { Metadata } from "next";
import Link from "next/link";
import { AnnualTimeLordTool } from "@/components/AnnualTimeLordTool";
import { createPageMetadata } from "@/lib/metadata";

export const metadata: Metadata = createPageMetadata({ title: "Annual Profection & Time Lord Calculator", description: "Calculate your current annual profection house and traditional time-lord planet, then learn what the activated year asks you to examine.", path: "/annual-time-lord" });

export default function AnnualTimeLordPage() {
  return <><section className="wood-panel py-18 md:py-24"><div className="mx-auto max-w-5xl px-6 text-center"><p className="font-ui text-xs font-semibold uppercase tracking-[0.22em] text-gold/72">Free traditional astrology tool</p><h1 className="mt-4 font-heading text-4xl font-semibold text-ivory md:text-6xl">Your Annual Time Lord</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed text-ivory/65">Discover which whole-sign house and planet govern the year between your last birthday and the next.</p></div></section><section className="bg-midnight py-14 md:py-20"><div className="mx-auto max-w-6xl px-6"><AnnualTimeLordTool /></div></section><section className="parchment-surface py-16 md:py-24"><div className="mx-auto max-w-3xl px-6"><p className="font-ui text-xs font-semibold uppercase tracking-[0.18em] text-gold-dark/78">How to read the result</p><h2 className="mt-3 font-heading text-3xl font-semibold text-aubergine md:text-5xl">The activated house names the field. The time lord manages it.</h2><div className="mt-6 space-y-5 text-base leading-relaxed text-ink/66"><p>Annual profections do not predict one event. They create hierarchy. The natal chart contains many promises at once; the profected house tells you which area has become louder during the current birthday year.</p><p>The time lord must then be judged in your natal chart and current sky. A Venus year can emphasize partnership, livelihood, home, creativity, or another topic depending on the houses Venus rules. That is why a calculator is a beginning rather than a complete forecast.</p><p>Continue with our researched guide to <Link href="/blog/annual-profections-time-lord-year" className="text-aubergine underline decoration-gold underline-offset-4">annual profections and the lord of the year</Link>.</p></div></div></section></>;
}
